---
# tasks file for user-role

- include_vars: users.yml

- name: Create users with home directory
  user: name={{ item.username }} shell=/bin/bash createhome=yes comment='Created by Ansible'
  with_items: '{{ users }}'

#- name: Setup | authorized key upload
#  authorized_key: user={{ item.username }}
#  key: "{{ lookup('file', 'files/{{ item.username }}.pub') }}"
#  when: '{{ item.use_sudo }} == True'
# with_items: '{{ users }}'

 
